apiVersion: v1
kind: Pod
metadata:
  name: multitennat-database-engine
  namespace: {{ .Values.namespace.name | quote }}
  labels:
     app: database-engine
spec:
  containers:
  - name: {{ .Values.postgrescontainer.name | quote }}
    image: {{ .Values.postgrescontainer.image | quote }}
    ports:
    - containerPort: {{ .Values.postgrescontainer.port }}
    env:  
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: databaseengine-postgres-cred
            key: postgres-db
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: databaseengine-postgres-cred
            key: postgres-user
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: databaseengine-postgres-cred
            key: postgres-password
    volumeMounts:
      - name: db-home
        mountPath: /var/lib/postgresql/
      # - name: db-config-volume 
      #   mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: db-home
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.name | quote}}
    # - name: db-config-volume
    #   configMap:
    #     name: database-config
    #     defaultMode: 0777
   
