apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | quote}}
  namespace: {{ .Values.namespace.name | quote }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage | quote}}

